apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xui0r3y0b-java-quarkus
  janus-idp.io/tekton: xui0r3y0b-java-quarkus
  backstage.io/kubernetes-id: xui0r3y0b-java-quarkus
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: xui0r3y0b-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
